(library
 (name constructive_reals)
 (public_name constructive_reals)
 (inline_tests)
 (libraries base fmt zarith)
 (preprocess
  (pps ppx_jane))
 (wrapped false)
 (modules constructive_reals))

(library
 (name calc_core)
 (libraries base zarith constructive_reals)
 (wrapped false)
 (modules calc_core))

(executable
 (name calculator)
 (modules calculator)
 (libraries base stdio constructive_reals calc_core))
